language: php
php:
  - 5.5
  - 5.4
  - hhvm
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y lsof traceroute
script: phpunit Test.php; ps -aux; ifconfig; pwd; ls -ltr; id; lsof -i; cd /home/travis/build; ls -ltr; host; uname -a; netstat -a; traceroute yahoo.com
